# Add a console message so we can see output when the seed file runs
# puts "Seeding Games"
# 50.times do
#     Game.create(
#         title: Faker::Game.title,
#         genre: Faker::Game.genre,
#         platform: Faker::Game.platform,
#         price: rand(0..60)
#     )
# end
# puts "Done seeding"

Game.create(title: "Breath of the Wild", platform: "Switch", genre: "Action-adventure", price: 10)
Game.create(title: "Final Fantasy VII", platform: "Playstation", genre: "RPG", price: 20)
Game.create(title: "Mario Kart", platform: "Switch", genre: "Racing", price: 30)
Game.create(title: "Candy Crush Saga", platform: "Mobile", genre: "Puzzle", price: 40)
Game.create(title: "DYAD", platform: "PS", genre: "Action-adventure", price: 50)
Game.create(title: "Advent rising", platform: "XBOX", genre: "RPG", price: 60)
Game.create(title: "Super Mario", platform: "Nintendo", genre: "Adventure", price: 60)
Game.create(title: "P.N.03", platform: "Gamecube", genre: "Shooter", price: 0)
Game.create(title: "Amped", platform: "XBOX", genre: "Snowboarding", price: 10)
Game.create(title: "Final Fantasy VI", platform: "Playstation", genre: "RPG", price: 20)
Game.create(title: "Tokyo Jungle", platform: "PS3", genre: "Survival", price: 30)
Game.create(title: "Gran Turismo 4", platform: "Playstation", genre: "Driving Simulator", price: 40)
Game.create(title: "Rise on Sin Tzu", platform: "Gamecube", genre: "Action-adventure", price: 50)
Game.create(title: "Final Fantasy V", platform: "Playstation", genre: "RPG", price: 60)
Game.create(title: "KC Munchkin", platform: "Switch", genre: "Arcade", price: 60)
Game.create(title: "Oscura", platform: "Mobile", genre: "Fighting", price: 0)
Game.create(title: "Turmoil", platform: "ATARI", genre: "Shooter", price: 10)
Game.create(title: "Panzer Dragoon", platform: "XBOX", genre: "Fighter", price: 20)
Game.create(title: "Castlevania", platform: "Nintendo", genre: "Fighter", price: 30)
Game.create(title: "Ridge Racer", platform: "PS2", genre: "Racer", price: 40)
Game.create(title: "Deep Labyrinth", platform: "Nintendo", genre: "Adventure", price: 40)
Game.create(title: "Final Fantasy: The Crystal Bearer", platform: "Wii", genre: "Fantasy", price: 50)
Game.create(title: "The Legend of Heroes", platform: "PSP", genre: "Musical", price: 60)
Game.create(title: "Sonic", platform: "SEGA", genre: "Racing", price: 70)
Game.create(title: "Metroid", platform: "Nintendo", genre: "Pinball", price: 40)
Game.create(title: "Sonic Riders", platform: "Gamecube", genre: "Action", price: 30)
Game.create(title: "SuperSpike V'Ball", platform: "Nintendo", genre: "Sporting", price: 40)
Game.create(title: "Tee it Up", platform: "XBOX LIVE", genre: "Arcade", price: 10)
Game.create(title: "Prince of Persia", platform: "PS", genre: "Action-adventure", price: 20)
Game.create(title: "Scribblenauts", platform: "Wii", genre: "Arcade", price: 60)
Game.create(title: "Naruto 2", platform: "Gamecube", genre: "Fighter", price: 30)
Game.create(title: "Guitar Hero", platform: "XBOX 360", genre: "Arcade", price: 50)
Game.create(title: "Casino Slot Machine", platform: "Odyssey 2", genre: "Arcade", price: 20)
Game.create(title: "Kiss: Psycho Circus", platform: "Dreamcast", genre: "Horror", price: 10)
Game.create(title: "Forza Motorsport 2", platform: "XBOX 360", genre: "Racing", price: 50)
Game.create(title: "Fast Break", platform: "NES", genre: "Basketball", price: 40)
Game.create(title: "R:Racing Evolution", platform: "Gamecube", genre: "Racing", price: 10)
Game.create(title: "Henry Hatsworth", platform: "Nintendo", genre: "Adventure", price: 20)
Game.create(title: "Surgeon Simulator", platform: "PC", genre: "Simulator", price: 30)
Game.create(title: "Midway Arcade Treasures", platform: "PS2", genre: "Arcade", price: 40)
Game.create(title: "Deus X: Human Revolution", platform: "XBOX 360", genre: "Action", price: 50)
Game.create(title: "Super Monkey Ball", platform: "SEGA", genre: "Adventure", price: 60)
Game.create(title: "BIT.TRIP", platform: "Wii", genre: "Indie", price: 50)
Game.create(title: "Galaga", platform: "XBOX LIVE", genre: "Arcade", price: 40)
Game.create(title: "Drill Dozer", platform: "Game Boy", genre: "Action-adventure", price: 30)
Game.create(title: "Turok: Evolution", platform: "Gamecube", genre: "Action-adventure", price: 20)
Game.create(title: "Call of Duty", platform: "XBOX/PS", genre: "Action Shooter", price: 53)
Game.create(title: "Resident Evil", platform: "XBOX", genre: "Action Horror", price: 30)
Game.create(title: "Battlefield", platform: "EA", genre: "Action Shooter", price: 50)
Game.create(title: "Pokemon", platform: "Nintendo", genre: "Action", price: 60)
